### ISSUE TITLE
Wanky layouts for some articles in mobile +  unclosable audio popup + small feature idea

### ISSUE THREAD

**Issue by paoloricciuti** [nick-barth/myqueue#1]
Hi, congrats on the winning on the svelte hackaton. I was starting to use your webapp (great idea btw) and i've noticed some thing that could be improved layout wise

![image](https://github.com/nick-barth/myqueue/assets/26281609/8fb5a40e-aa2a-4c35-95f3-9349e82fa67d)

As you can see some articles are non-legible from mobile.

Also once you open an audio there's no way to close the popup at the bottom (i know it's not needed but i'm crazy and it kinda irritates me that i cannot close it).

Lastly i'll just propose a feature: let the user train a custom voice is he knows the author of the article and assign that voice to the reader of the article. In my case i know the article was written by Ryan Carniato and there's enaugh content on the web to train a model on his voice. (just a random idea, i know it would be difficult)

**Comment by paoloricciuti** [comment]
Also also i might be able to work on the first two issues if you accept PRs

**Comment by nick-barth** [comment]
Hey @paoloricciuti, I'm sorry I missed these!  We're currently working on a redesign, and we love the idea of training voices based on specific authors.  I'm going to close this for now, I'll ping you once we've updated!
